# Generated by Django 5.1.4 on 2025-01-08 20:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(default='', null=True)),
                ('address', models.TextField(default='', null=True)),
                ('zipCode', models.TextField(default='', null=True)),
                ('city', models.TextField(default='', null=True)),
                ('latitude', models.FloatField(default=0.0, null=True)),
                ('longitude', models.FloatField(default=0.0, null=True)),
                ('estimatedValue', models.FloatField(default=0.0, null=True)),
                ('noRelevantRisks', models.IntegerField(default=0, null=True)),
                ('noHandledRisks', models.IntegerField(default=0, null=True)),
                ('totalFinancialRisk', models.FloatField(default=0.0, null=True)),
            ],
        ),
    ]
